server:
  port: 14625
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mashion
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://localhost:27017/mashion
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update