server:
  port: 11111
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recommendation
    username: yfzm
    password: recommendation
  data:
    mongodb:
      uri: mongodb://localhost:27017/recommendation
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create